default: &default
  adapter: postgresql
  encoding: unicode
  username: postgresql
  password: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: page_pal

test:
  <<: *default
  database: pagepal_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
