default: &default
  adapter: postgresql
  encoding: unicode
  username: postgresql
  password: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: page_pal

test:
  <<: *default
  database: pagepal_test

production:
  <<: *default
  database: pagepal_production
  username: postgres_prod
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
